---
# tasks file for engonzal.proxmoxct
- include_tasks: inventory.yml

- name: Get existing container facts
  include_tasks: inventory_exists.yml
  when: pve_container_exists

- name: Provision Container
  include_tasks: provision.yml
  when: not pve_container_exists

- name: Configure mounts
  include_tasks: mounts.yml
  when:
    - not pve_container_exists
    - pve_custom_mounts is defined
