---
# handlers file for engonzal.proxmoxct
- name: Start container
  proxmox:
    vmid: "{{ pve_vmid | default(pve_new_vmid) | int }}"
    api_user: "{{ pve_apiuser }}"
    api_password: "{{ pve_apipass }}"
    api_host: "{{ pve_api_host }}"
    state: started
  delegate_to: localhost
  register: pve_info_state

- name: Set vmid
  set_fact:
    pve_new_vmid:  "{{ pve_info.msg.split(' ')[2] }}"
  when: pve_vmid is not defined
